aa_teams:
  version: 0.1
  rule_create_date: '2026-01-20'
  rule_modified_date: '2026-01-20'
  s3_checkpoints_uri: aa_teams/data_quality/checkpoints/teams_processed
  s3_expectations_uri: aa_teams/data_quality/expectations/teams_processed
  s3_validations_uri: aa_teams/data_quality/validations/teams_processed
  data_docs_prefix: aa_teams/data_quality/html_report/teams_processed
  repository:
  - url: https://github.com/pasrichashivam/aws_glue_pipeline
    name: aateams 
  expectations:
    expectation_suite_name: aa_teams_processed
    rules:
    - rule_definition:
        expectation_type: expect_column_values_to_be_of_type
        kwargs:
          column: id
          type_: IntegerType
      critical: true
    - rule_definition:
        expectation_type: expect_column_values_to_be_between
        kwargs:
          column: id
          min_value: 0
          max_value: 20
      critical: true
    - rule_definition:
        expectation_type: expect_compound_column_to_be_unique
        kwargs:
          column_list: 
            - id
            - parent_id
      critical: true
